apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: docker.csmpl.com:5000/node-app:v1
      ports:
        - containerPort: 8080
